name: Main
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2.3.4

    - name: Run Hugo
      uses: crazy-max/ghaction-hugo@v1.4.0
      with:
        extended: true

    - name: Deploy to GitHub pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        keep_history: true
        allow_empty_commit: false
        build_dir: public
        commit_message: ${{ github['event']['commits'][0]['message'] }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
